apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.namespace.name }} 
  name: {{ .Values.namespace.name }} 
  namespace: {{ .Values.namespace.name }} 
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: {{ .Values.namespace.name }} 
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.namespace.name }} 
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Values.namespace.name }} 
        resources:
{{ toYaml .Values.resources | indent 12 }}
