apiVersion: v1
items:
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    creationTimestamp: "2021-12-10T16:27:10Z"
    name: {{ .Values.namespace.name }} 
    namespace: {{ .Values.namespace.name }}
  spec:
    maxReplicas: 20
    minReplicas: 5
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: {{ .Values.namespace.name }} 
    targetCPUUtilizationPercentage: 50
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""