namespace:
  name: imdb-mongodb
 
service:
  port: 4000
  type: ClusterIP

image:
  repository: adhirkirtikar/imdb-mongodb
  tag: 0.27
  pullPolicy: IfNotPresent

replicaCount: 5

resources:
  requests:
    cpu: 50m
    memory: 256Mi

dns:
  dnsname: imdb-mongodb.dec96de7-e7f9-4b06-9f21-2e0f053e0bfd.k8s.civo.com